### ISSUE TITLE
review draft "Serverless Computing: One Step Forward, Two Steps Back" by Joseph M. Hellerstein and others

### ISSUE THREAD

**Issue by thiagomanel** [ufcg-lsd/serverless-reading#2]
it is a draft of a CIDR submission https://arxiv.org/abs/1812.03651
a post about the paper https://databeta.wordpress.com/2018/12/13/serverless-computing-one-step-fw-two-steps-back/

reasons to review: I like the work of the first author, his group is strong. Also, it is important to read a critique every now and then.

**Comment by thiagomanel** [comment]
see http://muratbuffalo.blogspot.com/2019/01/paper-review-serverless-computing-one.html

**Comment by danielfireman** [comment]
and https://blog.acolyer.org/2019/01/14/serverless-computing-one-step-forward-two-steps-back/

**Comment by thiagomanel** [comment]
slides https://speakerdeck.com/jhellerstein/serverless-computing-one-step-forward-two-steps-back
